version: "3.7"

services:
    # image project
    app:
        container_name: laravel-api-ead
        build:
            context: .
            dockerfile: Dockerfile
        image: especializati/laravel9-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel_api_ead
    
    # nginx
    nginx:
        container_name: laravel-api-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel_api_ead

    # db mysql
    mysql:
        container_name: laravel-api-mysql
        image: mysql:8.0
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - "3388:3306"
        networks: 
            - laravel_api_ead

    # queue
    queue:
        container_name: laravel-api-queue
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
            - app
        networks: 
            - laravel_api_ead

    # redis
    redis:
        container_name: laravel-api-redis
        image: redis:latest
        networks: 
            - laravel_api_ead

networks: 
    laravel_api_ead:
        driver: bridge